#!/bin/bash

# Helper for searching code base without searching through external code

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd $DIR
    exec ack "$@" \
        --ignore-directory .tox \
        --ignore-directory dist \
        --ignore-directory build \
        --ignore-directory lifx_photons_core.egg-info \
        --ignore-directory tools \
        --ignore-directory docs/.photons-docs \
        --ignore-directory docs/res \
        --ignore-directory docs/gh-pages \
        --ignore-directory docs/lifx_photons_docs.egg-info \
        --ignore-directory examples/.lifx \
        --ignore-directory generate_photons_messages/.generate_photons_messages \
        --ignore-directory apps/tile_arranger/static/node_modules \
        --ignore-directory apps/tile_arranger/static/dist \
        --ignore-directory apps/tile_arranger/.lifx 
)
