#!/bin/bash

set -e

# Helper for searching code base without searching through external code

cd "$(git rev-parse --show-toplevel)"

exec ack "$@" \
    --ignore-directory .tox \
    --ignore-directory .venv \
    --ignore-directory .mypy_cache \
    --ignore-directory .dmypy.json \
    --ignore-directory dist \
    --ignore-directory build \
    --ignore-directory "*.egg-info" \
    --ignore-directory tools/.bootstrap-venv \
    --ignore-directory docs/res \
    --ignore-directory docs/gh-pages \
    --ignore-directory examples/.lifx \
    --ignore-directory generate_photons_messages/.generate_photons_messages \
    --ignore-directory apps/interactor/docker/.harpoon \
    --ignore-directory modules/.mypy_cache \
    --ignore-directory apps/arranger/.mypy_cache \
    --ignore-directory apps/interactor/.mypy_cache \
    --ignore-file is:uv.lock \
