#!/bin/bash

cd $(git rev-parse --show-toplevel)

./tools/black/setup_venv

./tools/black/.black/bin/noy_black modules apps/arranger/arranger apps/interactor/interactor

if ! which prettier >/dev/null; then
  echo "Couldn't find prettier, not formatting javascript files"
else
  echo ""
  echo "==="
  echo "--- Formatting javascript"
  echo "==="
  echo ""
  prettier --write "apps/arranger/arranger/static/js/**"
fi
