"""add_scene_info

Revision ID: aab549c5cdbd
Revises: 119f5f1434f7
Create Date: 2018-07-29 10:40:29.913320

"""

# revision identifiers, used by Alembic.
revision = "aab549c5cdbd"
down_revision = "119f5f1434f7"
branch_labels = None
depends_on = None

import sqlalchemy as sa
from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sceneinfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.String(length=64), nullable=True),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sceneinfo_uuid"), "sceneinfo", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sceneinfo_uuid"), table_name="sceneinfo")
    op.drop_table("sceneinfo")
    # ### end Alembic commands ###
