#!/usr/bin/env python3


(
    __import__("venvstarter")
    .manager("generate_photons_messages")
    .add_pypi_deps("lifx-photons-messages-generator==0.6.8")
    .min_python(3.12)
    .add_env(SRC=("{venv_parent}", "public-protocol", "protocol.yml"))
    .add_env(ADJUSTMENTS=("{venv_parent}", "adjustments.yml"))
    .add_env(OUTPUT_FOLDER=("{venv_parent}", "..", "..", "modules", "photons_messages"))
    .run()
)
