#!/usr/bin/env python3

(
    __import__("venvstarter")
    .manager("lifx")
    .add_local_dep(
        "{here}",
        "..",
        "modules",
        version_file=(
            "photons_app",
            "__init__.py",
        ),
        name="lifx-photons-core=={version}",
    )
    .min_python("3.7")
    .run()
)
