#!/usr/bin/env python3

import shutil
import runpy
import os

this_dir = os.path.abspath(os.path.dirname(__file__))

black_pyproject_toml = os.path.join(this_dir, "black", "pyproject.toml")
noy_black_version = runpy.run_path(os.path.join(this_dir, "noy_black", "noy_black", "__init__.py"))[
    "VERSION"
]

black_version = None
with open(black_pyproject_toml, "r") as fle:
    for line in fle:
        if line.startswith("version ="):
            black_version = line.split("=", 1)[1].strip()[1:-1]
            break

if not black_version:
    raise Exception("Failed to determine the version of black")

from venvstarter import ignite

ignite(
    __file__,
    "black",
    deps=[
        f"-e file:{this_dir}/black#egg=black=={black_version}",
        f"-e file:{this_dir}/noy_black#egg=noy_black=={noy_black_version}",
    ],
    min_python_version=3.6,
)
