#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [[ ! -e $DIR/.black ]]; then
    $DIR/setup_venv
fi

case "${@: -1}" in
    */tests/*)
        exec $DIR/.black/bin/noy_black "$@"
        ;;
    *) 
        exec $DIR/.black/bin/black "$@"
        ;;
esac