#!/usr/bin/env python3

from venvstarter import manager

(
    __import__("venvstarter")
    .manager("mypy")
    .named(".types")
    .add_pypi_deps("mypy==0.931", "noseOfYeti==2.2.0")
    .add_local_dep(
        "{here}",
        "..",
        "modules",
        version_file=(
            "photons_app",
            "__init__.py",
        ),
        name="lifx-photons-core=={version}",
        with_tests=True,
    )
    .min_python("3.7")
    .run()
)
