#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case "${@: -1}" in
    */tests/*)
        exec $DIR/black noy_black "$@"
        ;;
    *) 
        exec $DIR/black black "$@"
        ;;
esac
