#!/usr/bin/env python3

from venvstarter import manager

m = manager("photons-docs")

m.add_local_dep(
    "{here}",
    "..",
    "modules",
    editable=True,
    version_file=("photons_app", "__init__.py"),
    name="lifx-photons-core=={version}",
)

m.add_local_dep(
    "{here}",
    editable=True,
    version_file=("photons_docs", "__init__.py"),
    name="lifx-photons-docs=={version}",
)

m.add_env(LIFX_CONFIG=("{here}", "docs.yml"))

m.run()
