#!/usr/bin/env python3

import runpy
import os

this_dir = os.path.abspath(os.path.dirname(__file__))
src_dir = os.path.join(this_dir, "..")

nylon_version = runpy.run_path(os.path.join(this_dir, "photons_docs", "__init__.py"))["VERSION"]

from venvstarter import ignite
ignite(__file__, "photons-docs"
    , deps = [
        f"-e file:{src_dir}#egg=lifx-photons-core"
      , f"-e file:{this_dir}#egg=lifx-photons-docs=={nylon_version}"
      ]
    , env = {"LIFX_CONFIG": os.environ.get("LIFX_CONFIG", "{venv_parent}/docs.yml")}
    , min_python_version = 3.6
    )
